export const stateResources = [
  { name: 'Alabama', abbr: 'AL', noticeName: 'Preliminary Notice to Owner', formUrl: 'https://www.levelset.com/preliminary-notice/alabama-preliminary-notice-faqs/', statuteUrl: 'https://alison.legislature.state.alabama.us/code-of-alabama/1975/35/11/35-11-210',
    requiredInfo: ['Claimant name/address/role', 'Owner name/address', 'GC name/address', 'Property description', 'Labor/material furnished', 'Amount owed/contract amount'],
    recipients: ['Owner', 'General Contractor'],
    deadlines: ['Send within 30 days of first unpaid labor/materials on residential; 4 months lien file deadline on commercial'],
    wording: ['State you are providing labor/material to the project and seek payment'],
    delivery: ['Certified mail recommended']
  },
  { name: 'Alaska', abbr: 'AK', noticeName: 'Notice of Right to Lien', formUrl: 'https://courts.alaska.gov/forms/docs/civ-107.pdf', statuteUrl: 'https://law.alaska.gov/statutes/34.35.064',
    requiredInfo: ['Claimant name/address', 'Owner name/address', 'Hiring party', 'Property description', 'Labor/material furnished', 'Amount claimed'],
    recipients: ['Owner', 'Original Contractor'],
    deadlines: ['Give notice before recording lien; best practice within 15 days of first furnishing'],
    wording: ['State intent to claim a lien and describe the labor/materials'],
    delivery: ['Certified mail or personal service with proof']
  },
  { name: 'Arizona', abbr: 'AZ', noticeName: '20-Day Preliminary Notice', formUrl: 'https://roc.az.gov/sites/default/files/forms/20-day_preliminary_notice.pdf', statuteUrl: 'https://www.azleg.gov/ars/33/00992-01.htm',
    requiredInfo: ['Claimant name/address and role', 'Owner name/address', 'Original contractor name', 'Construction lender name (if any)', 'Estimated total price of labor/materials', 'General description of labor/materials and jobsite'],
    recipients: ['Owner', 'Original Contractor', 'Construction Lender (if any)'],
    deadlines: ['Serve within 20 days of first furnishing for full protection', 'Late notice covers work 20 days prior to service and after'],
    wording: ['Include statutory warning per A.R.S. § 33-992.01(C)'],
    delivery: ['Certified or registered mail, or personal service with proof']
  },
  { name: 'Arkansas', abbr: 'AR', noticeName: 'Notice to Owner and Contractor', formUrl: 'https://www.levelset.com/preliminary-notice/arkansas-preliminary-notice-faqs/', statuteUrl: 'https://law.justia.com/codes/arkansas/title-18/subtitle-4/chapter-44/subchapter-1/section-18-44-115/',
    requiredInfo: ['Claimant name/address and role', 'Owner/GC names', 'Property description', 'Labor/material furnished', 'Amount owed'],
    recipients: ['Owner', 'General Contractor'],
    deadlines: ['Serve before supplying or within 75 days of last item'],
    wording: ['Identify the project, hiring party, and amount due'],
    delivery: ['Certified mail']
  },
  { name: 'California', abbr: 'CA', noticeName: '20-Day Preliminary Notice', formUrl: 'https://www.cslb.ca.gov/Resources/FormsAndApplications/PreliminaryNoticePrivateWorks.pdf', statuteUrl: 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=8202.&lawCode=CIV',
    requiredInfo: ['Claimant name, address, and relation to the job', 'Owner name/address', 'Direct contractor name/address', 'Construction lender name/address (if any)', 'General job description and site address', 'Estimated total price of labor/materials furnished/to be furnished'],
    recipients: ['Owner', 'Direct Contractor', 'Construction Lender (if any)'],
    deadlines: ['Serve within 20 days of first furnishing to fully protect rights', 'Late notice covers only work 20 days prior to service and forward'],
    wording: ['Include statutory warning language per Cal. Civ. Code § 8202(b)', 'State the estimated total price and identify required parties per § 8102'],
    delivery: ['Certified, registered, or express mail; or personal delivery with proof (Cal. Civ. Code § 8110)']
  },
  { name: 'Colorado', abbr: 'CO', noticeName: 'Notice of Intent to Lien (NOI)', formUrl: 'https://leg.colorado.gov/sites/default/files/images/olls/crs2023-title-38.pdf#page=150', statuteUrl: 'https://law.justia.com/codes/colorado/2024/title-38/article-22/section-38-22-109/',
    requiredInfo: ['Claimant name/address', 'Owner name/address', 'GC name', 'Property description', 'Amount claimed'],
    recipients: ['Owner', 'General Contractor'],
    deadlines: ['Serve NOI at least 10 days before recording lien statement'],
    wording: ['State intent to file lien and amount claimed'],
    delivery: ['Certified mail or personal service with proof']
  },
  { name: 'Connecticut', abbr: 'CT', noticeName: 'Notice of Intent to Claim a Lien', formUrl: 'https://portal.ct.gov/-/media/DCP/Occupational-Licensing-Forms/MechanicsLienForm.pdf', statuteUrl: 'https://www.cga.ct.gov/current/pub/chap_847.htm#sec_49-34',
    requiredInfo: ['Claimant name/address', 'Owner name/address', 'Hiring party', 'Property description', 'Amount claimed'],
    recipients: ['Owner', 'Original Contractor'],
    deadlines: ['Serve within 90 days of cessation of work/improvement'],
    wording: ['State intent to claim a mechanic’s lien with amount and property description'],
    delivery: ['By registered or certified mail or personal service']
  },
  { name: 'Delaware', abbr: 'DE', noticeName: 'Notice to Owner (1–4 unit residential)', formUrl: 'https://www.levelset.com/preliminary-notice/delaware-preliminary-notice-faqs/', statuteUrl: 'https://delcode.delaware.gov/title25/c027/sc01/index.html',
    requiredInfo: ['Claimant name/address', 'Owner name/address', 'Hiring party', 'Labor/material description', 'Amount due'],
    recipients: ['Owner'],
    deadlines: ['Serve within 60 days of first furnishing on 1–4 unit residential'],
    wording: ['State labor/material furnished and intent to claim lien if unpaid'],
    delivery: ['Certified mail']
  },
  { name: 'Florida', abbr: 'FL', noticeName: 'Notice to Owner (NTO)', formUrl: 'https://www.floridabar.org/wp-content/uploads/2017/04/Notice-to-Owner-Form.pdf', statuteUrl: 'http://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0700-0799/0713/Sections/0713.06.html',
    requiredInfo: ['Claimant name/address and contracting party', 'Owner name/address; property description', 'General contractor name/address', 'Services/materials furnished or to be furnished', 'Amount owed/to be owed', 'Statement preserving lien rights under Fla. Stat. Ch. 713'],
    recipients: ['Owner', 'General Contractor', 'Lender (if any)'],
    deadlines: ['Serve within 45 days of first furnishing', 'Late NTO protects only work 45 days before service and after'],
    wording: ['Include statutory warning language per Fla. Stat. § 713.06(2)(c)', 'Describe labor/materials and property sufficiently to identify the project'],
    delivery: ['Certified mail with return receipt or other method with proof of delivery (Fla. Stat. § 713.18)']
  },
  { name: 'Georgia', abbr: 'GA', noticeName: 'Notice to Contractor / 60-Day Notice', formUrl: 'https://www.levelset.com/preliminary-notice/georgia/', statuteUrl: 'https://law.justia.com/codes/georgia/title-44/chapter-14/article-8/part-3/section-44-14-361-5/',
    requiredInfo: ['Claimant name/address and hiring party', 'Project description and location', 'Owner and contractor names/addresses', 'Statement of labor/materials furnished and amounts'],
    recipients: ['Contractor (when Notice of Commencement is filed)', 'Owner (copy recommended)'],
    deadlines: ['Notice to Contractor: within 30 days of first furnishing if Notice of Commencement is filed', '60-Day Notice for each month’s unpaid work on projects with Notice of Commencement'],
    wording: ['Use statutory form language per O.C.G.A. § 44-14-361.5'],
    delivery: ['Certified mail, statutory overnight delivery, or hand delivery with proof']
  },
  { name: 'Hawaii', abbr: 'HI', noticeName: 'Notice of Right to Lien', formUrl: 'https://www.courts.state.hi.us/docs/court_forms/jims1/SC-P-311.pdf', statuteUrl: 'https://www.capitol.hawaii.gov/hrscurrent/Vol10_Ch0446-0465/HRS0507/HRS_0507-0045.htm',
    requiredInfo: ['Claimant name/address', 'Owner name/address', 'Hiring party', 'Property description', 'Labor/material furnished', 'Amount claimed'],
    recipients: ['Owner', 'Original Contractor'],
    deadlines: ['Within 45 days of first furnishing to secure priority before completion'],
    wording: ['State intent to claim lien and describe labor/materials'],
    delivery: ['Certified mail or personal service with proof']
  },
  { name: 'Idaho', abbr: 'ID', noticeName: 'Preliminary Notice', formUrl: 'https://isc.idaho.gov/sites/default/files/forms/mchanics_lien_prenotice.pdf', statuteUrl: 'https://legislature.idaho.gov/statutesrules/idstat/title45/t45ch5/sect45-507/',
    requiredInfo: ['Claimant name/address', 'Owner name/address', 'Hiring party', 'Labor/material description', 'Estimated amount'],
    recipients: ['Owner', 'Lender (if any)', 'Original Contractor'],
    deadlines: ['Within 30 days of first delivery of materials (best practice for subs/suppliers)'],
    wording: ['State intent to claim lien and identify project/labor/material'],
    delivery: ['Certified mail']
  },
  { name: 'Illinois', abbr: 'IL', noticeName: 'Subcontractor Notice (60/90-day)', formUrl: 'https://www.levelset.com/preliminary-notice/illinois-preliminary-notice-faqs/', statuteUrl: 'https://www.ilga.gov/legislation/ilcs/fulltext.asp?DocName=077000600K24',
    requiredInfo: ['Claimant name/address', 'Hiring party', 'Owner name', 'Balance due and description of work'],
    recipients: ['Owner', 'Lender (if any)'],
    deadlines: ['60-day notice to owner (owner-occupied 4 units or less)', '90-day notice on other projects to preserve lien'],
    wording: ['State amount due and work performed per 770 ILCS 60/24'],
    delivery: ['Certified mail or personal service']
  },
  { name: 'Indiana', abbr: 'IN', noticeName: 'Pre-Lien Notice (owner-occupied residential)', formUrl: 'https://www.levelset.com/preliminary-notice/indiana-preliminary-notice-faqs/', statuteUrl: 'https://iga.in.gov/laws/2024/ic/titles/32#32-28',
    requiredInfo: ['Claimant name/address', 'Owner name/address', 'Hiring party', 'Description of labor/material', 'Property description'],
    recipients: ['Owner'],
    deadlines: ['Within 30 days of first furnishing (new build); 60 days (remodel) for owner-occupied residential'],
    wording: ['Reference intent to hold lien and identify property/work'],
    delivery: ['Certified mail']
  },
  { name: 'Iowa', abbr: 'IA', noticeName: 'Preliminary Notice (MNLR filing)', formUrl: 'https://sos.iowa.gov/business/pdf/MechanicsLienPrelimNotice.pdf', statuteUrl: 'https://www.legis.iowa.gov/docs/code/572.pdf',
    requiredInfo: ['Claimant name/address', 'Owner name/address', 'Hiring party', 'Property legal description', 'Labor/material description'],
    recipients: ['Filed electronically (MNLR)'],
    deadlines: ['Post to MNLR within 10 days of first furnishing (residential best practice)'],
    wording: ['State claim and property details per Iowa Code 572'],
    delivery: ['Electronic filing to MNLR']
  },
  { name: 'Kansas', abbr: 'KS', noticeName: 'No statutory preliminary (lien timing)', formUrl: 'https://www.levelset.com/blog/kansas-mechanics-lien/', statuteUrl: 'http://kslegislature.org/li/b2023_24/statute/060_011_0000_article/060_011_0003_section/',
    requiredInfo: [], recipients: [], deadlines: [], wording: [], delivery: []
  },
  { name: 'Kentucky', abbr: 'KY', noticeName: 'Notice of Furnishing (owner-occupied)', formUrl: 'https://www.levelset.com/preliminary-notice/kentucky-preliminary-notice-faqs/', statuteUrl: 'https://apps.legislature.ky.gov/law/statutes/statute.aspx?id=52094',
    requiredInfo: ['Claimant name/address', 'Owner name', 'Description of labor/material', 'Amount due'],
    recipients: ['Owner (owner-occupied 1–2 unit)'],
    deadlines: ['Within 75 days of last furnishing for owner-occupied 1–2 unit'],
    wording: ['State intent to claim lien and describe work/amount'],
    delivery: ['Certified mail']
  },
  { name: 'Louisiana', abbr: 'LA', noticeName: 'Notice of Nonpayment / Lien Rights', formUrl: 'https://legis.la.gov/Legis/Law.aspx?d=109249', statuteUrl: 'https://legis.la.gov/Legis/Law.aspx?d=109249',
    requiredInfo: ['Claimant name/address', 'Owner/GC names', 'Property description', 'Labor/material and amount due'],
    recipients: ['Owner', 'Contractor'],
    deadlines: ['Monthly notices often required before lien; supplier to residential must notice before delivery'],
    wording: ['State nonpayment and intent to preserve privilege'],
    delivery: ['Certified mail']
  },
  { name: 'Maine', abbr: 'ME', noticeName: 'No preliminary notice (lien timing)', formUrl: 'https://www.levelset.com/blog/maine-mechanics-lien/', statuteUrl: 'https://legislature.maine.gov/statutes/10/title10ch603sec0.html',
    requiredInfo: [], recipients: [], deadlines: [], wording: [], delivery: []
  },
  { name: 'Maryland', abbr: 'MD', noticeName: 'Notice to Owner (subs/suppliers)', formUrl: 'https://www.levelset.com/preliminary-notice/maryland-preliminary-notice-faqs/', statuteUrl: 'https://mgaleg.maryland.gov/mgawebsite/Laws/StatuteText?article=grp&section=9-104',
    requiredInfo: ['Claimant name/address', 'Owner name/address', 'Hiring party', 'Amount due', 'Description of work'],
    recipients: ['Owner'],
    deadlines: ['Within 120 days after last work'],
    wording: ['State intent to claim lien and amount per Md. Real Prop. § 9-104'],
    delivery: ['Registered mail, certified mail, or personal service']
  },
  { name: 'Massachusetts', abbr: 'MA', noticeName: 'Notice of Identification / Notice of Contract', formUrl: 'https://www.mass.gov/doc/notice-of-contract-form/download', statuteUrl: 'https://malegislature.gov/Laws/GeneralLaws/PartIII/TitleI/Chapter254',
    requiredInfo: ['Claimant name/address', 'Owner and GC names', 'Property description', 'Contract amount/description'],
    recipients: ['Recording at registry (Notice of Contract); Notice of Identification to GC'],
    deadlines: ['Notice of Identification within 30 days of first furnishing (subs)', 'Record Notice of Contract before or within stated statutory period'],
    wording: ['Use statutory form text in c.254'],
    delivery: ['Record/serve per statute; certified mail to GC for Notice of ID']
  },
  { name: 'Michigan', abbr: 'MI', noticeName: 'Notice of Furnishing', formUrl: 'https://www.michigan.gov/documents/dtmb/Notice_of_Furnishing_476877_7.pdf', statuteUrl: 'http://legislature.mi.gov/doc.aspx?mcl-570-1109',
    requiredInfo: ['Claimant name/address', 'Designee/owner/GC from Notice of Commencement', 'Description of labor/material', 'Estimated amount'],
    recipients: ['Owner’s designee/GC/owner per Notice of Commencement'],
    deadlines: ['Within 20 days of first furnishing (unless no NOC posted)'],
    wording: ['Use statutory Notice of Furnishing language per MCL 570.1109'],
    delivery: ['Personal service or certified mail']
  },
  { name: 'Minnesota', abbr: 'MN', noticeName: 'Pre-Lien Notice', formUrl: 'https://www.revisor.mn.gov/statutes/cite/514.011/pdf', statuteUrl: 'https://www.revisor.mn.gov/statutes/cite/514.011',
    requiredInfo: ['Statutory pre-lien warning text in contract/first invoice', 'Describe services/materials and parties'],
    recipients: ['Owner'],
    deadlines: ['Within 45 days of first furnishing (subs/suppliers)'],
    wording: ['Statutory warning per Minn. Stat. § 514.011'],
    delivery: ['Include in contract/invoice; deliver to owner']
  },
  { name: 'Mississippi', abbr: 'MS', noticeName: 'Pre-Lien Notice (owner-occupied)', formUrl: 'https://www.levelset.com/preliminary-notice/mississippi-preliminary-notice-faqs/', statuteUrl: 'https://law.justia.com/codes/mississippi/title-85/chapter-7/article-7/section-85-7-409/',
    requiredInfo: ['Claimant name/address', 'Owner name/address', 'Work description', 'Amount due'],
    recipients: ['Owner (owner-occupied single-family)'],
    deadlines: ['10 days before filing lien for owner-occupied residential'],
    wording: ['State intent to file lien and amount due'],
    delivery: ['Certified mail']
  },
  { name: 'Missouri', abbr: 'MO', noticeName: 'Notice to Owner / 10-Day Notice', formUrl: 'https://www.courts.mo.gov/file.jsp?id=52612', statuteUrl: 'https://revisor.mo.gov/main/Home.aspx?chapter=429',
    requiredInfo: ['Claimant name/address', 'Owner name/address', 'GC name', 'Description of work', 'Amount due'],
    recipients: ['Owner (and GC for 10-day notice)'],
    deadlines: ['Original contractor residential notice at contract; subs: 10-day notice before lien filing'],
    wording: ['Use statutory language per RSMo 429.012 and 429.100'],
    delivery: ['Certified mail or personal service']
  },
  { name: 'Montana', abbr: 'MT', noticeName: 'Notice of Right to Claim a Lien', formUrl: 'https://www.levelset.com/preliminary-notice/montana-preliminary-notice-faqs/', statuteUrl: 'https://leg.mt.gov/bills/mca/title_0710/chapter_0030/part_0050/section_0031/0710-0030-0050-0031.html',
    requiredInfo: ['Claimant name/address', 'Owner name/address', 'Hiring party', 'Description of labor/material', 'Amount'],
    recipients: ['Owner'],
    deadlines: ['Within 20 days of first furnishing if Notice of Completion is filed; otherwise before lien'],
    wording: ['State right to claim lien and describe work'],
    delivery: ['Certified mail']
  },
  { name: 'Nebraska', abbr: 'NE', noticeName: 'Notice of Right to Assert a Lien', formUrl: 'https://www.levelset.com/preliminary-notice/nebraska-preliminary-notice-faqs/', statuteUrl: 'https://nebraskalegislature.gov/laws/statutes.php?statute=52-1309',
    requiredInfo: ['Claimant name/address', 'Owner name', 'Hiring party', 'Description of work', 'Amount'],
    recipients: ['Owner'],
    deadlines: ['Before filing lien; best within 20 days of first furnishing'],
    wording: ['State intent to claim lien and describe work'],
    delivery: ['Certified mail']
  },
  { name: 'Nevada', abbr: 'NV', noticeName: 'Notice of Right to Lien', formUrl: 'https://www.leg.state.nv.us/Division/Legal/LawLibrary/NAC/NAC-108.html', statuteUrl: 'https://www.leg.state.nv.us/NRS/NRS-108.html#NRS108Sec245',
    requiredInfo: ['Claimant name/address', 'Owner name/address', 'GC name', 'Lender (if any)', 'Description of labor/material', 'Amount'],
    recipients: ['Owner', 'Original Contractor', 'Construction Lender (if any)'],
    deadlines: ['Within 31 days of first furnishing'],
    wording: ['Use statutory form per NRS 108.245'],
    delivery: ['Certified mail']
  },
  { name: 'New Hampshire', abbr: 'NH', noticeName: 'No preliminary notice (lien timing)', formUrl: 'https://www.gencourt.state.nh.us/rsa/html/XLVII/447/447-mrg.htm', statuteUrl: 'https://www.gencourt.state.nh.us/rsa/html/XLVII/447/',
    requiredInfo: [], recipients: [], deadlines: [], wording: [], delivery: []
  },
  { name: 'New Jersey', abbr: 'NJ', noticeName: 'Notice of Unpaid Balance (residential)', formUrl: 'https://nj.gov/dobi/banklicensing/forms/NoticeofUnpaidBalance.pdf', statuteUrl: 'https://lis.njleg.state.nj.us/nxt/gateway.dll?f=templates&fn=default.htm&vid=Publish:10.1048/Enu',
    requiredInfo: ['Claimant name/address', 'Owner/GC names', 'Property description', 'Work and amount due'],
    recipients: ['Owner', 'GC', 'Filed and arbitrated for residential'],
    deadlines: ['Before filing lien on residential; follow Lien Law timelines'],
    wording: ['Use NUB statutory language'],
    delivery: ['File/serve per statute; certified mail']
  },
  { name: 'New Mexico', abbr: 'NM', noticeName: 'Preliminary Notice of Right to Claim Lien', formUrl: 'https://www.rld.nm.gov/uploads/FileLinks/4e883b8b8fa84a6cbc56726cd93c83c9/Mechanics_Lien_Pre_lien_Notice.pdf', statuteUrl: 'https://law.justia.com/codes/new-mexico/chapter-48/article-2/section-48-2-2/',
    requiredInfo: ['Claimant name/address', 'Owner name', 'Hiring party', 'Property description', 'Work description', 'Amount'],
    recipients: ['Owner', 'Original Contractor', 'Lender (if any)'],
    deadlines: ['Within 60 days of first furnishing for subs/suppliers'],
    wording: ['State right to claim lien and describe labor/material'],
    delivery: ['Certified mail']
  },
  { name: 'New York', abbr: 'NY', noticeName: 'No preliminary notice (lien timing)', formUrl: null, statuteUrl: 'https://www.nysenate.gov/legislation/laws/LIE/3',
    requiredInfo: [], recipients: [], deadlines: [], wording: [], delivery: []
  },
  { name: 'North Carolina', abbr: 'NC', noticeName: 'Notice to Lien Agent (online)', formUrl: 'https://www.liensnc.com/', statuteUrl: 'https://www.ncleg.gov/EnactedLegislation/Statutes/HTML/BySection/Chapter_44A/GS_44A-11.2.html',
    requiredInfo: ['Claimant name/address', 'Owner', 'Hiring party', 'Property description'],
    recipients: ['Lien Agent (via LiensNC)'],
    deadlines: ['Within 15 days of first furnishing for best protection'],
    wording: ['Use portal fields; identify property and contracting parties'],
    delivery: ['Electronic via LiensNC']
  },
  { name: 'North Dakota', abbr: 'ND', noticeName: 'No preliminary notice (lien timing)', formUrl: null, statuteUrl: 'https://www.legis.nd.gov/cencode/t35c27.pdf',
    requiredInfo: [], recipients: [], deadlines: [], wording: [], delivery: []
  },
  { name: 'Ohio', abbr: 'OH', noticeName: 'Notice of Furnishing', formUrl: 'https://www.com.ohio.gov/documents/LiensNoticeOfFurnishing.pdf', statuteUrl: 'https://codes.ohio.gov/ohio-revised-code/section-1311.05',
    requiredInfo: ['Claimant name/address', 'Owner/GC from Notice of Commencement', 'Description of work/materials'],
    recipients: ['Owner', 'GC', 'Others listed in NOC'],
    deadlines: ['Within 21 days of first furnishing after NOC is recorded'],
    wording: ['Use statutory Notice of Furnishing language'],
    delivery: ['Certified mail']
  },
  { name: 'Oklahoma', abbr: 'OK', noticeName: 'Pre-Lien Notice', formUrl: 'https://www.levelset.com/preliminary-notice/oklahoma-preliminary-notice-faqs/', statuteUrl: 'https://www.oscn.net/applications/oscn/DeliverDocument.asp?CiteID=441064',
    requiredInfo: ['Claimant name/address', 'Owner name', 'Hiring party', 'Property description', 'Amount due', 'Work description'],
    recipients: ['Owner', 'GC'],
    deadlines: ['Within 75 days of last furnishing for projects over $10k'],
    wording: ['State intent to file lien and amount due'],
    delivery: ['Certified mail with return receipt']
  },
  { name: 'Oregon', abbr: 'OR', noticeName: 'Notice of Right to Lien', formUrl: 'https://www.oregon.gov/ccb/Documents/Notice%20of%20right%20to%20lien.pdf', statuteUrl: 'https://oregon.public.law/statutes/ors_87.021',
    requiredInfo: ['Claimant name/address', 'Owner name', 'Hiring party', 'Property description', 'Description of materials/services'],
    recipients: ['Owner'],
    deadlines: ['Within 8 business days of first furnishing (subs/suppliers)'],
    wording: ['Use statutory form per ORS 87.021'],
    delivery: ['Certified mail or personal service']
  },
  { name: 'Pennsylvania', abbr: 'PA', noticeName: 'Notice of Furnishing (if NOC filed)', formUrl: 'https://www.scnd.pa.gov/', statuteUrl: 'https://www.legis.state.pa.us/WU01/LI/LI/CT/HTM/49/00.015.001.000..HTM',
    requiredInfo: ['Claimant name/address', 'Owner/GC names', 'Property description', 'Description of labor/material'],
    recipients: ['Owner', 'GC (when Notice of Commencement is filed)'],
    deadlines: ['Within 45 days of first furnishing'],
    wording: ['Follow 49 P.S. § 1501.2 content requirements'],
    delivery: ['Certified mail; filing via State Construction Notices Directory as applicable']
  },
  { name: 'Rhode Island', abbr: 'RI', noticeName: 'Notice of Possible Mechanic’s Lien', formUrl: 'https://www.courts.ri.gov/PublicResources/forms/Superior%20Court%20Forms/Mechanics%20Lien%20-%20Notice%20of%20Possible%20Mechanics%20Lien.pdf', statuteUrl: 'https://law.justia.com/codes/rhode-island/title-34/chapter-34-28/section-34-28-4.1/',
    requiredInfo: ['Claimant name/address', 'Owner name/address', 'Hiring party', 'Property description', 'Amount due', 'Work description'],
    recipients: ['Owner'],
    deadlines: ['Within 200 days of last work (commercial)'],
    wording: ['Use statutory notice form per § 34-28-4.1'],
    delivery: ['Certified mail']
  },
  { name: 'South Carolina', abbr: 'SC', noticeName: 'Notice of Furnishing Labor or Materials', formUrl: 'https://www.sccourts.org/forms/pdf/SCCA455.pdf', statuteUrl: 'https://www.scstatehouse.gov/code/t29c005.php',
    requiredInfo: ['Claimant name/address', 'Owner/GC', 'Property description', 'Labor/material description', 'Amount'],
    recipients: ['Owner', 'GC'],
    deadlines: ['Serve within 90 days of last furnishing before lien'],
    wording: ['State labor/material furnished and amount'],
    delivery: ['Certified mail or personal service']
  },
  { name: 'South Dakota', abbr: 'SD', noticeName: 'No preliminary notice (lien timing)', formUrl: null, statuteUrl: 'https://sdlegislature.gov/Statutes/Codified_Laws/2060794',
    requiredInfo: [], recipients: [], deadlines: [], wording: [], delivery: []
  },
  { name: 'Tennessee', abbr: 'TN', noticeName: 'Notice of Nonpayment / Notice to Owner', formUrl: 'https://www.tn.gov/content/dam/tn/commerce/documents/regboards/contractors/forms/Notice_to_Owner.pdf', statuteUrl: 'https://law.justia.com/codes/tennessee/title-66/chapter-11/part-1/section-66-11-145/',
    requiredInfo: ['Claimant name/address', 'Owner/GC names', 'Project description', 'Month(s) unpaid and amounts'],
    recipients: ['Owner', 'GC'],
    deadlines: ['By 90 days from month-end for unpaid work (monthly)'],
    wording: ['Use statutory nonpayment language per Tenn. Code § 66-11-145'],
    delivery: ['Certified mail']
  },
  { name: 'Texas', abbr: 'TX', noticeName: 'Monthly Notice to Owner/GC', formUrl: 'https://www.texaslienlaws.com/forms', statuteUrl: 'https://statutes.capitol.texas.gov/Docs/PR/htm/PR.53.htm',
    requiredInfo: ['Claimant name, address, and role (sub/supplier)', 'Original contractor (GC) name', 'Owner name and project address', 'Month(s) and nature of labor/material furnished', 'Amount unpaid for each month', 'Statement that this is a notice under Tex. Prop. Code Ch. 53'],
    recipients: ['Owner', 'Original Contractor (GC)'],
    deadlines: ['Residential/unpaid progress: mail by 15th day of 2nd month after each month of unpaid work', 'Most commercial: mail by 15th day of 3rd month after each month of unpaid work', 'Retainage notice: by 30th day after completion/termination/abandonment of the contract (Tex. Prop. Code § 53.057)'],
    wording: ['Include statutory fund-trapping language per Tex. Prop. Code § 53.056', 'Identify month, amount, parties, and that payment is unpaid'],
    delivery: ['Registered or certified mail to owner and GC (Tex. Prop. Code § 53.003)']
  },
  { name: 'Utah', abbr: 'UT', noticeName: 'Preliminary Notice (SCR)', formUrl: 'https://secure.utah.gov/constructionnotice/site/welcome.html', statuteUrl: 'https://le.utah.gov/xcode/Title38/Chapter1A/38-1a.html',
    requiredInfo: ['Claimant name/address', 'Owner/GC names', 'Property description', 'Labor/material description'],
    recipients: ['Filed in State Construction Registry'],
    deadlines: ['Before or soon after first furnishing to cover subsequent work'],
    wording: ['Enter required fields in SCR'],
    delivery: ['Electronic filing']
  },
  { name: 'Vermont', abbr: 'VT', noticeName: 'No preliminary notice (lien timing)', formUrl: null, statuteUrl: 'https://legislature.vermont.gov/statutes/section/09/051/01921',
    requiredInfo: [], recipients: [], deadlines: [], wording: [], delivery: []
  },
  { name: 'Virginia', abbr: 'VA', noticeName: 'No preliminary notice (lien timing)', formUrl: null, statuteUrl: 'https://law.lis.virginia.gov/vacode/title43/chapter1/',
    requiredInfo: [], recipients: [], deadlines: [], wording: [], delivery: []
  },
  { name: 'Washington', abbr: 'WA', noticeName: 'Notice to Owner / Right to Claim Lien', formUrl: 'https://www.lni.wa.gov/forms-publications/f625-007-000.pdf', statuteUrl: 'https://app.leg.wa.gov/RCW/default.aspx?cite=60.04.031',
    requiredInfo: ['Claimant name/address', 'Owner/GC names', 'Description of labor/material', 'Property address'],
    recipients: ['Owner', 'General Contractor'],
    deadlines: ['Within 60 days of first furnishing (new construction)', 'Within 10 days of first furnishing (owner-occupied remodel)'],
    wording: ['Use statutory form per RCW 60.04.031'],
    delivery: ['Certified or registered mail or personal service']
  },
  { name: 'West Virginia', abbr: 'WV', noticeName: 'No preliminary notice (lien timing)', formUrl: null, statuteUrl: 'https://code.wvlegislature.gov/38-2/',
    requiredInfo: [], recipients: [], deadlines: [], wording: [], delivery: []
  },
  { name: 'Wisconsin', abbr: 'WI', noticeName: 'Preliminary Notice / Notice of Lien Rights', formUrl: 'https://www.wicourts.gov/formdisplay/CV-524.pdf', statuteUrl: 'https://docs.legis.wisconsin.gov/statutes/statutes/779/i/02',
    requiredInfo: ['Prelien notice text to owner identifying claimant and that lien rights are claimed'],
    recipients: ['Owner'],
    deadlines: ['Within 60 days of first furnishing (subs/suppliers)'],
    wording: ['Use statutory notice language per Wis. Stat. § 779.02(2)'],
    delivery: ['Certified mail']
  },
  { name: 'Wyoming', abbr: 'WY', noticeName: 'No preliminary notice (lien timing)', formUrl: null, statuteUrl: 'https://wyoleg.gov/WyomingStatutes/Title29/Chapter2/Section29-2-111',
    requiredInfo: [], recipients: [], deadlines: [], wording: [], delivery: []
  },
];
